root: . # Root directory of your GitBook project
structure:
  readme: README.md # Main introduction file
  summary: SUMMARY.md # Table of contents
  langs: # Optional for multi-language support
    - en
    - es
plugins:
  - logo # Plugin to add a logo to the book
  - fontsettings # Optional plugin for font customization
  - search # Built-in search functionality
  - highlight # Code highlighting

output:
  folder: _book # Output folder for built files
